title: "what's Up!"
description: 全球热点信息周刊 · Global Weekly Digest
baseurl: "/whats-up"
url: "https://jackson-chu-sys.github.io"
markdown: kramdown
defaults:
  - scope:
      path: ""
    values:
      layout: default
